module Firefly.names {

	class NameSet {
		system: string;
		maleNames: string[];
		femaleNames: string[];
		surnames: string[];
	}

	var systems: NameSet[] = [
		{
			system: 'Core Planet',
			maleNames: [
				"Winston",
				"Wilson",
				"Ward",
				"Warren",
				"Thomas",
				"Spencer",
				"Sinclair",
				"Montgomery",
				"Phillip",
				"Howard",
				"Mitchell",
				"Nicholas",
				"Percy",
				"Reginald",
				"Francis",
				"Gregory",
				"Nathaniel",
				"Quentin",
				"Atticus",
				"Cuthbert",
				"Crispin",
				"Hugo",
				"Conrad",
			],
			femaleNames: [
				"Kendall",
				"Genevieve",
				"Beatrice",
				"Yvonne",
				"Elizabeth",
				"Meredith",
				"Jacqueline",
				"Lucille",
				"Victoria",
				"Arabella",
				"Camilla",
				"Cordelia",
				"Ophelia",
				"Augusta",
				"Octavia",
				"Belinda",
				"Helena",
				"Florence",
				"Sophia",
				"Rebecca",
				"Carlotta",
				"Phillipa",
				"Rowena",
			],
			surnames: [
				"Bates",
				"Yeatman",
				"Wynn",
				"Wright",
				"Woodruff",
				"Barker",
				"Thornton",
				"Underwood",
				"Tuttle",
				"Townsley",
				"Townshend",
				"Stuart",
				"Tate",
				"Sutton",
				"King",
				"Stanford",
				"Rutherford",
				"Sexton",
				"Richmond",
				"Quinn",
				"Pearson",
				"Powell",
				"Andersen",
			],
		},
		{
			system: 'Red Sun System',
			maleNames: [
				"Sherman",
				"Russel",
				"Seymour",
				"Ambrose",
				"Billy",
				"Cole",
				"Cassidy",
				"Clarence",
				"Elijah",
				"Gus",
				"Hank",
				"Jesse",
				"Luke",
				"Owen",
				"Sam",
				"Travis",
				"Zeke",
				"Bai",
				"Chang",
				"Chao",
				"Chen",
				"Hai",
				"Han",
			],
			femaleNames: [
				"Chow",
				"Chun",
				"Fung",
				"Hua",
				"Jun",
				"Lee",
				"Lian",
				"Mei",
				"Shun",
				"Ting",
				"Wen",
				"Yan",
				"Yu",
				"Abigail",
				"Ada",
				"Charlotte",
				"Daisy",
				"Ellie",
				"Hannah",
				"Hattie",
				"Judith",
				"Maybelle",
				"Nelly",
			],
			surnames: [
				"Sullivan",
				"Skinner",
				"Richards",
				"Puckett",
				"Nicholson",
				"Mucklebreed",
				"Michaels",
				"McCoy",
				"McGee",
				"McDonnell",
				"Lewis",
				"Kaine",
				"Smith",
				"Brown",
				"Lee",
				"Wilson",
				"Taylor",
				"Davis",
				"Lee",
				"Harris",
				"Clark",
				"Young",
				"Adams",
			],
		},
		{
			system: 'Georgia System',
			maleNames: [
				"Earnest",
				"Felix",
				"Lucky",
				"Clem",
				"Mick",
				"Sully",
				"Cal",
				"Judd",
				"Ned",
				"Theo",
				"Charlie",
				"Gus",
				"Jeb",
				"Ray",
				"Hal",
				"Nat",
				"Ty",
				"Will",
				"Sam",
				"Kit",
				"Jack",
				"Andy",
				"Chet",
			],
			femaleNames: [
				"Chastity",
				"Charity",
				"Clemency",
				"Mercy",
				"Temperance",
				"Constance",
				"Hope",
				"Grace",
				"Faith",
				"Honor",
				"Cornelia",
				"Sissy",
				"Maggie",
				"Abby",
				"Frankie",
				"Poppy",
				"Penny",
				"Tessie",
				"Nellie",
				"Tillie",
				"Sadie",
				"Lulu",
				"Aggie",
			],
			surnames: [
				"Oakley",
				"Masterson",
				"Starr",
				"Courtright",
				"Doolin",
				"Pickett",
				"Bart",
				"Ketchum",
				"Dalton",
				"Ford",
				"Cody",
				"Cannary",
				"Madsen",
				"Allison",
				"Younger",
				"Douglas",
				"Holliday",
				"Borne",
				"Horner",
				"McJunkin",
				"Clanton",
				"Ware",
				"Hardin",
			],
		},
		{
			system: 'Blue Sun System',
			maleNames: [
				"Mark",
				"Paul",
				"Robert",
				"William",
				"Donald",
				"George",
				"Kenneth",
				"Steven",
				"Brian",
				"Edward",
				"Joseph",
				"Charles",
				"Richard",
				"David",
				"Christopher",
				"Ronald",
				"James",
				"John",
				"Anthony",
				"Thomas",
				"Michael",
				"Jason",
				"Tyler",
			],
			femaleNames: [
				"Patricia",
				"Linda",
				"Barbara",
				"Jennifer",
				"Susan",
				"Margaret",
				"Dorothy",
				"Lisa",
				"Nancy",
				"Karen",
				"Betty",
				"Sandra",
				"Donna",
				"Carol",
				"Ruth",
				"Sharon",
				"Michelle",
				"Laura",
				"Kimberly",
				"Deborah",
				"Helen",
				"Ava",
				"Natalie",
			],
			surnames: [
				"Archer",
				"Bond",
				"Cartwright",
				"Dyer",
				"Fletcher",
				"Harper",
				"Horner",
				"Knight",
				"Mason",
				"Piper",
				"Planter",
				"Porter",
				"Potter",
				"Sawyer",
				"Seaman",
				"Shoemaker",
				"Spencer",
				"Skinner",
				"Tanner",
				"Taylor",
				"Thatcher",
				"Wainwright",
				"Weaver",
			],
		},
		{
			system: 'Kalidasa System',
			maleNames: [
				"Hassan",
				"Elias",
				"Adolfo",
				"Noel",
				"Lucas",
				"Viktor",
				"Malik",
				"Davu",
				"Marcus",
				"Conley",
				"Juan",
				"Bedros",
				"Liam",
				"Jayden",
				"Emeka",
				"Wataru",
				"Cooper",
				"Lorenzo",
				"Noah",
				"Ayo",
				"Mateo",
				"Bunmei",
				"Isaiah",
			],
			femaleNames: [
				"Fatima",
				"Maryam",
				"Jada",
				"Zahra",
				"Iwalani",
				"Magda",
				"Kirabo",
				"Sanaa",
				"Remika",
				"Gisela",
				"Lena",
				"Abiba",
				"Nomusa",
				"Gabrielle",
				"Anya",
				"Maria",
				"Liliana",
				"Chloe",
				"Tahlia",
				"Breena",
				"Cyrah",
				"Olga",
				"Elyse",
			],
			surnames: [
				"Vargas",
				"Dupont",
				"Novak",
				"Garcia",
				"Nielsen",
				"Ivanov",
				"Petrovavich",
				"Singh",
				"Isa",
				"Karlsson",
				"Antoniak",
				"Hashimoto",
				"Roux",
				"Giovanni",
				"Van der Meer",
				"Ndiaye",
				"O’Sullivan",
				"Schumacher",
				"Kawaguchi",
				"Gallo",
				"Costa",
				"Okoro",
				"De Wit",
			],
		},
	];

	export enum Gender {
		Male,
		Female,
	}

	export class Bio {
		gender: Gender;
		name: string;
		system: string;
	}

	function rand(max: number): number {
		return Math.floor(Math.random() * max);
	}

	var fireflyNameModule = angular.module('fireflyNames', []);
	fireflyNameModule.factory('names',() => systems);
	fireflyNameModule.factory('bioGenerator',() => (system: string = ''): Bio => {
		var nameSet = _.find(systems, { system: system });
		if (!nameSet) {
			nameSet = systems[rand(systems.length)];
		}

		var gender = rand(2) == 0 ? Gender.Male : Gender.Female;

		return {
			gender: gender,
			system: nameSet.system,
			name: (gender == Gender.Male ? nameSet.maleNames[rand(nameSet.maleNames.length)] : nameSet.femaleNames[rand(nameSet.femaleNames.length)]) + ' ' + nameSet.surnames[rand(nameSet.surnames.length)],
		}
	});

}